import Head from 'next/head'
import { Inter } from '@next/font/google'
import Login from '@/components/Auth/login';
import SignUp from '@/components/Auth/signup';

const inter = Inter({ subsets: ['latin'] })

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>No Despacito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-5'>
        <SignUp />
      </main>
    </>
  )
}
